"""
Epoch AI Benchmarking Hub adapter — the spine of the benchmarks
channel, and per brief §7.1 the one adapter that had to be built first
and completely.

Two ways in, in the brief's own order of preference:

  1. the published client library (`pip install epochai`), which reads
     the same records through Epoch's Airtable API;
  2. the bulk CC-BY data bundle at epoch.ai/data/benchmark_data.zip,
     which is the documented fallback and contains exactly the same
     CSVs the hub renders.

The bundle is tried second and is what runs in CI, because it needs no
extra dependency and no API round-trips; the client library is used
when it happens to be installed, which keeps the brief's stated
preference honest without making `epochai` a hard requirement of the
whole pipeline.

Two things this adapter is careful about, because they are the reason
the channel exists at all:

**Conditions travel with the number.** Epoch documents its own run
conditions (chat/instruct variants, API-default temperature, zero-shot
chain-of-thought, empty system prompt) and records a reasoning-effort
suffix on the model version. All of that is written into
`conditions`; a record is never emitted with an empty one.

**Epoch's own runs and Epoch's redistribution of someone else's runs
are not the same evidence.** Files without an `_external` suffix are
Epoch's internal evaluations (`measuredBy: thirdparty`, evaluator
"Epoch AI", harness `inspect`). Files with it are numbers Epoch
collected from a leaderboard or a vendor announcement, and the
evaluator is taken from the row's own `Source` column — including the
handful of rows whose source is a vendor's own announcement, which are
correctly recorded as `measuredBy: vendor` and are exactly the material
the vendor-versus-third-party gap trigger feeds on.
"""

from __future__ import annotations

import csv
import io
import re
import sys
import time
import zipfile
from pathlib import Path

from ..constants import (
    EPOCH_ATTRIBUTION,
    EPOCH_BACKFILL_START,
    EPOCH_BULK_ZIP_URL,
    EPOCH_LICENSE,
    FETCH_TIMEOUT,
    STATE_DIR,
    USER_AGENT,
)

CACHE_DIR = STATE_DIR / "cache"
CACHE_FILE = CACHE_DIR / "epoch_benchmark_data.zip"
# The bundle is regenerated by Epoch at most daily; re-downloading 2 MB
# on every hourly run would be rude and pointless.
CACHE_TTL_SECONDS = 12 * 3600

EVALUATOR_EPOCH = "Epoch AI"
PUBLISHER = "Epoch AI"
HUB_URL = "https://epoch.ai/benchmarks"


class EpochSource:
    """One CSV inside the bundle, mapped onto one registry slug."""

    def __init__(
        self,
        filename: str,
        slug: str,
        score_column: str,
        scale: float = 1.0,
        *,
        internal: bool = True,
        variant: str = "",
        tools: bool = False,
        default_evaluator: str = "",
    ):
        self.filename = filename
        self.slug = slug
        self.score_column = score_column
        # Epoch's own `scale` factor from benchmark_metadata.csv: raw *
        # scale is the score as a 0-1 fraction.
        self.scale = scale
        self.internal = internal
        # Which cut of a benchmark this file is. FrontierMath ships four
        # incompatible private sets; a score without the set is noise.
        self.variant = variant
        self.tools = tools
        self.default_evaluator = default_evaluator or (
            EVALUATOR_EPOCH if internal else "Unattributed leaderboard"
        )


# Only the twelve benchmarks in /benchmarks.json are ingested. Epoch
# carries 80+; the rest are outside the declared scope (brief §14.1,
# text/reasoning only) and are silently skipped rather than dropped with
# a warning, because they were never asked for.
EPOCH_SOURCES: tuple[EpochSource, ...] = (
    EpochSource("gpqa_diamond.csv", "gpqa-diamond", "Best score (across scorers)", 1.0),
    EpochSource(
        "frontiermath.csv",
        "frontiermath",
        "Best score (across scorers)",
        1.0,
        variant="FrontierMath 2025-02-28 (private)",
    ),
    EpochSource(
        "frontiermath_tier_4.csv",
        "frontiermath",
        "Best score (across scorers)",
        1.0,
        variant="FrontierMath Tier 4, 2025-07-01 (private)",
    ),
    EpochSource(
        "frontiermath_tiers_1_3_v2.csv",
        "frontiermath",
        "Best score (across scorers)",
        1.0,
        variant="FrontierMath Tiers 1-3 v2 (private)",
    ),
    EpochSource(
        "frontiermath_tier_4_v2.csv",
        "frontiermath",
        "Best score (across scorers)",
        1.0,
        variant="FrontierMath Tier 4 v2 (private)",
    ),
    EpochSource(
        "swe_bench_verified.csv",
        "swe-bench-verified",
        "Best score (across scorers)",
        1.0,
        tools=True,
    ),
    EpochSource(
        "terminalbench_external.csv",
        "terminal-bench",
        "Accuracy mean",
        1.0,
        internal=False,
        tools=True,
        default_evaluator="Terminal-Bench leaderboard",
    ),
    EpochSource(
        "arc_agi_2_external.csv",
        "arc-agi-2",
        "Score",
        1.0,
        internal=False,
        default_evaluator="ARC Prize leaderboard",
    ),
    EpochSource(
        "live_bench_external.csv",
        "livebench",
        "Global average",
        1.0,
        internal=False,
        default_evaluator="LiveBench Leaderboard",
    ),
    EpochSource(
        "aider_polyglot_external.csv",
        "aider-polyglot",
        "Percent correct",
        0.01,
        internal=False,
        tools=True,
        default_evaluator="Aider LLM Leaderboards",
    ),
    EpochSource(
        "hle_external.csv",
        "hle",
        "Accuracy",
        1.0,
        internal=False,
        default_evaluator="Humanity's Last Exam leaderboard",
    ),
    EpochSource(
        "os_world_external.csv",
        "osworld",
        "Score",
        0.01,
        internal=False,
        tools=True,
        default_evaluator="OSWorld leaderboard",
    ),
)

EPOCH_FILE_TO_SLUG = {source.filename: source.slug for source in EPOCH_SOURCES}

# Where a measurement date can hide, best first. `Started at` is when
# Epoch actually ran the eval; `Release date` is the *model's* release
# and only the last resort, since it says nothing about when the number
# was produced.
DATE_COLUMNS = (
    "Started at",
    "Run date",
    "Date of evaluation",
    "Date added",
    "Created",
    "Release date",
)

# Rows whose Source names the model's own lab are vendor claims, not
# independent measurements, whatever file they arrive in.
VENDOR_SOURCE_HINTS = (
    "announcement",
    "annoucement",  # Epoch's own spelling in os_world_external.csv
    "blog post",
    "model card",
    "system card",
    "press release",
)


def download_bundle(force: bool = False) -> Path:
    """Fetch (and cache) the CC-BY bundle. Kept separate from parsing so
    a run can be replayed offline against the cached zip."""
    import requests

    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    fresh = (
        CACHE_FILE.exists()
        and (time.time() - CACHE_FILE.stat().st_mtime) < CACHE_TTL_SECONDS
    )
    if fresh and not force:
        return CACHE_FILE

    response = requests.get(
        EPOCH_BULK_ZIP_URL,
        timeout=FETCH_TIMEOUT * 3,
        headers={"User-Agent": USER_AGENT},
    )
    response.raise_for_status()
    CACHE_FILE.write_bytes(response.content)
    return CACHE_FILE


def best_date(row: dict) -> str:
    """ISO date (YYYY-MM-DD) for when this number was produced."""
    for column in DATE_COLUMNS:
        value = (row.get(column) or "").strip()
        if value:
            return value[:10]
    return ""


def _float(value: str) -> float | None:
    try:
        return float(str(value).strip())
    except (TypeError, ValueError):
        return None


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")


def _conditions(source: EpochSource, row: dict, effort: str | None) -> dict:
    """Never empty. A score with no conditions is a number, not a
    finding (brief §4), so every record carries at least a sentence
    about how it was produced."""
    notes: list[str] = []
    if source.variant:
        notes.append(source.variant)
    for column, label in (
        ("Agent", "agent"),
        ("LiveBench Version", "question set"),
        ("Edit format", "edit format"),
        ("Notes", "note"),
        ("Notes (details)", "note"),
    ):
        value = (row.get(column) or "").strip()
        if value:
            notes.append(f"{label}: {value}")
    for column in ("stderr", "Accuracy SE", "Accuracy Standard Error"):
        value = _float(row.get(column, ""))
        if value is not None:
            notes.append(f"stderr {value:.3g}")
            break

    conditions: dict = {"tools": source.tools}
    if effort:
        conditions["reasoningEffort"] = effort
    if source.internal:
        # Epoch documents these for every internal run.
        conditions["shots"] = 0
        notes.append(
            "Epoch AI house conditions: zero-shot chain-of-thought, empty system "
            "prompt, API-default temperature, chat/instruct variant"
        )
    conditions["notes"] = "; ".join(notes) if notes else (
        f"Redistributed by Epoch AI from {source.default_evaluator}; "
        "run conditions not published per-row"
    )
    return conditions


def _evaluator_and_kind(source: EpochSource, row: dict) -> tuple[str, str]:
    """(evaluator, measuredBy) for one row."""
    if source.internal:
        return EVALUATOR_EPOCH, "thirdparty"

    raw = (row.get("Source") or "").strip()
    if not raw:
        return source.default_evaluator, "community"
    if raw.startswith("http"):
        return source.default_evaluator, "community"

    lowered = raw.lower()
    organisation = (row.get("Organization") or "").split(",")[0].strip()
    if organisation and organisation.split()[0].lower() in lowered:
        # The Source cell describes where the number came from
        # ("Anthropic annoucement" — Epoch's own typo); the evaluator
        # field wants the party that produced it. Strip the descriptor
        # and keep the organisation's own spelling of its name.
        return organisation, "vendor"
    return raw, "community"


def _source_url(source: EpochSource, row: dict) -> str:
    for column in ("Source link", "Source Link", "Log viewer", "Logs"):
        value = (row.get(column) or "").strip()
        if value.startswith("http"):
            return value
    raw = (row.get("Source") or "").strip()
    if raw.startswith("http"):
        return raw
    return HUB_URL


def measurement_id(slug: str, model_id: str, evaluator: str, measured_at: str) -> str:
    """`<benchmark>--<model>--<evaluator>--<YYYY-MM-DD>`, per §4."""
    return f"{slug}--{model_id}--{_slug(evaluator)}--{measured_at}"


def read_rows(bundle_path: Path | None = None) -> list[tuple[EpochSource, dict]]:
    """Every in-scope row in the bundle, unresolved and unnormalised."""
    path = bundle_path or download_bundle()
    rows: list[tuple[EpochSource, dict]] = []
    with zipfile.ZipFile(path) as bundle:
        available = set(bundle.namelist())
        for source in EPOCH_SOURCES:
            if source.filename not in available:
                print(
                    f"    epoch: {source.filename} missing from the bundle — skipped",
                    file=sys.stderr,
                )
                continue
            text = bundle.read(source.filename).decode("utf-8")
            for row in csv.DictReader(io.StringIO(text)):
                rows.append((source, row))
    return rows


def collect(
    registry,
    bundle_path: Path | None = None,
    *,
    since: str = EPOCH_BACKFILL_START,
) -> tuple[list[dict], list[dict]]:
    """Normalise the bundle into collection-shaped measurement records.

    Returns (measurements, unresolved). Unresolved entries are model
    names the registry could not place; they are parked by the caller
    and never invented into the collection.
    """
    measurements: list[dict] = []
    unresolved: list[dict] = []
    seen_unresolved: set[str] = set()

    from ..registry import effort_of

    for source, row in read_rows(bundle_path):
        benchmark = registry.resolve_benchmark(source.slug)
        if benchmark is None:
            continue  # slug not in the closed vocabulary: drop, never invent

        measured_at = best_date(row)
        if not measured_at or measured_at < since:
            continue

        raw_score = _float(row.get(source.score_column, ""))
        if raw_score is None:
            continue

        version = (row.get("Model version") or "").strip()
        if not version:
            continue

        model = registry.resolve_model(version)
        if model is None:
            if version not in seen_unresolved:
                seen_unresolved.add(version)
                unresolved.append(
                    {
                        "name": version,
                        "source": "epoch",
                        "benchmark": source.slug,
                        "organization": (row.get("Organization") or "").strip(),
                        "seenAt": measured_at,
                    }
                )
            continue

        fraction = raw_score * source.scale
        if benchmark.unit == "percent":
            value = round(fraction * 100, 2)
        else:
            # Elo and 0-100 composite scores are already in their own
            # unit; scaling them would be a silent unit error.
            value = round(raw_score, 3)

        effort = effort_of(version)
        evaluator, measured_by = _evaluator_and_kind(source, row)

        measurements.append(
            {
                "id": measurement_id(benchmark.slug, model.id, evaluator, measured_at),
                "model": model.id,
                "vendor": model.vendor,
                "benchmark": benchmark.slug,
                "metric": benchmark.metric,
                "value": value,
                "unit": benchmark.unit,
                "measuredBy": measured_by,
                "evaluator": evaluator,
                "harness": "inspect" if source.internal else None,
                "conditions": _conditions(source, row, effort),
                "measuredAt": measured_at,
                "sourceUrl": _source_url(source, row),
                "publisher": PUBLISHER,
                "license": EPOCH_LICENSE,
                "attribution": EPOCH_ATTRIBUTION,
            }
        )

    return measurements, unresolved
